// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "BCL Backend API",
    "version": "1"
  },
  "paths": {
    "/items": {
      "post": {
        "summary": "crearItem",
        "description": "",
        "operationId": "crearItem.post.items",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "get": {
        "summary": "listarItems",
        "description": "",
        "operationId": "listarItems.get.items",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/items/{id}": {
      "put": {
        "summary": "actualizarItem",
        "description": "",
        "operationId": "actualizarItem.put.items/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "delete": {
        "summary": "eliminarItem",
        "description": "",
        "operationId": "eliminarItem.delete.items/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "CursoProf": {
      "properties": {
        "tipo": {
          "title": "CursoProf.tipo",
          "type": "string"
        },
        "profesor": {
          "title": "CursoProf.profesor",
          "type": "string"
        },
        "curso": {
          "title": "CursoProf.curso",
          "type": "string"
        },
        "descripcion": {
          "title": "CursoProf.descripcion",
          "type": "string"
        },
        "duracion": {
          "title": "CursoProf.duracion",
          "type": "number"
        }
      },
      "required": [
        "tipo",
        "profesor",
        "curso"
      ],
      "additionalProperties": false,
      "title": "CursoProf",
      "type": "object"
    },
    "HorarioProfesor": {
      "properties": {
        "tipo": {
          "title": "HorarioProfesor.tipo",
          "type": "string"
        },
        "semana_profesor": {
          "title": "HorarioProfesor.semana_profesor",
          "type": "string"
        },
        "dia": {
          "title": "HorarioProfesor.dia",
          "type": "string"
        },
        "hora_inicio": {
          "title": "HorarioProfesor.hora_inicio",
          "type": "string"
        },
        "hora_fin": {
          "title": "HorarioProfesor.hora_fin",
          "type": "string"
        }
      },
      "required": [
        "tipo",
        "semana_profesor"
      ],
      "additionalProperties": false,
      "title": "HorarioProfesor",
      "type": "object"
    },
    "ReservaClase": {
      "properties": {
        "tipo": {
          "title": "ReservaClase.tipo",
          "type": "string"
        },
        "fecha_reserva": {
          "title": "ReservaClase.fecha_reserva",
          "type": "string"
        },
        "profesor": {
          "title": "ReservaClase.profesor",
          "type": "string"
        },
        "estudiante": {
          "title": "ReservaClase.estudiante",
          "type": "string"
        },
        "curso": {
          "title": "ReservaClase.curso",
          "type": "string"
        },
        "estado": {
          "title": "ReservaClase.estado",
          "type": "string"
        }
      },
      "required": [
        "tipo",
        "fecha_reserva"
      ],
      "additionalProperties": false,
      "title": "ReservaClase",
      "type": "object"
    },
    "CreateItemRequest": {
      "properties": {
        "tipo": {
          "title": "CreateItemRequest.tipo",
          "type": "string"
        }
      },
      "required": [
        "tipo"
      ],
      "additionalProperties": {},
      "title": "CreateItemRequest",
      "type": "object"
    },
    "UpdateItemRequest": {
      "additionalProperties": {},
      "title": "UpdateItemRequest",
      "type": "object"
    },
    "DeleteItemRequest": {
      "properties": {
        "id": {
          "title": "DeleteItemRequest.id",
          "type": "string"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false,
      "title": "DeleteItemRequest",
      "type": "object"
    },
    "ListItemsResponse": {
      "properties": {
        "items": {
          "items": {
            "title": "ListItemsResponse.items.[]"
          },
          "title": "ListItemsResponse.items",
          "type": "array"
        },
        "count": {
          "title": "ListItemsResponse.count",
          "type": "number"
        }
      },
      "required": [
        "items",
        "count"
      ],
      "additionalProperties": false,
      "title": "ListItemsResponse",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};